version: '3'

services:
  web:
    build: .
    ports: 
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
      - SECRET_KEY=postgres
      - DEBUG=True
      - ALLOWED_HOSTS=*
      

  db:
    image: postgres:13
    ports:
     - "5432:5432"
    volumes: 
     - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
